server:
  port: 9002

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customer;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  application:
    name: customer-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true
