server:
  port: 9003

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arun-stephen/java-spring-microservices/config-server-git/config-remote-store
          search-paths:
            - '*service'
  application:
    name: config-server