server:
  port: 9003

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:loan;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  application:
    name: loan-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true

logging:
  file: _logs/app.log